const mongoose = require("mongoose");

const notificationSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true
  },

  message: {
    type: String,
    required: true,
    trim: true
  },

  target: {
    type: String,
    enum: ["all", "parent"],
    default: "all"
  },

  parent: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    default: null
  },

  // Which specific child this notification is about, when it's an
  // auto-generated per-student event (new homework, a grade, a behavior
  // report, a board note) rather than a manually-authored broadcast —
  // lets the parent app show/filter "activity" per child. Null for
  // manually-authored admin/teacher broadcasts (createNotification).
  student: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Student",
    default: null
  },

  // "broadcast" = the existing manually-authored admin/teacher message
  // (createNotification). Everything else is auto-generated by a specific
  // teacher action — drives which icon the parent app shows.
  type: {
    type: String,
    enum: [
      "broadcast",
      "homework",
      "homeworkGrade",
      "behavior",
      "boardNote",
    ],
    default: "broadcast"
  },

  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true
  },

  school: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "School",
    required: true,
  },

}, { timestamps: true });

module.exports = mongoose.model("Notification", notificationSchema);