const mongoose = require("mongoose");

const notificationSchema = new mongoose.Schema({
  title: {
    type: String,
    required: true,
    trim: true
  },

  message: {
    type: String,
    required: true,
    trim: true
  },

  target: {
    type: String,
    enum: ["all", "parent", "student"],
    default: "all"
  },

  parent: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    default: null
  },

  // The student account a `target: "student"` copy belongs to. Students in
  // preparatory and secondary hold their own accounts, and everything that
  // reaches a parent reaches the child too — except a negative behaviour
  // note, which stays between the teacher and the parent.
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    default: null
  },

  // Narrows a `target: "all"` announcement to part of the school. Empty —
  // the default, and what every announcement written before stages existed
  // has — means the whole school, so nothing already sent changes meaning.
  // Set when the sender presides over some stages only: "everyone" then
  // means everyone they preside over, and a family in another stage never
  // sees it.
  stages: {
    type: [String],
    default: []
  },

  // Which specific child this notification is about, when it's an
  // auto-generated per-student event (new homework, a grade, a behavior
  // report, a board note) rather than a manually-authored broadcast —
  // lets the parent app show/filter "activity" per child. Null for
  // manually-authored admin/teacher broadcasts (createNotification).
  student: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Student",
    default: null
  },

  // "broadcast" = the existing manually-authored admin/teacher message
  // (createNotification). Everything else is auto-generated by a specific
  // teacher action — drives which icon the parent app shows.
  type: {
    type: String,
    enum: [
      "broadcast",
      "homework",
      "homeworkGrade",
      "behavior",
      "boardNote",
    ],
    default: "broadcast"
  },

  // Who has already seen this. A list rather than a single flag because a
  // target: "all" broadcast is one document shared by every parent in the
  // school — one parent reading it must not mark it read for everyone.
  readBy: [
    {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
    }
  ],

  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true
  },

  school: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "School",
    required: true,
  },

}, { timestamps: true });

module.exports = mongoose.model("Notification", notificationSchema);